name = "test-ground"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true
build_base_image = "golang:1.18.3"
go_version = "1.18"
enable_go_build_cache = true

[runners."local:docker"]
enabled = true


[[testcases]]
name = "test-sync"
instances = { min = 1, max = 100, default = 1 }